# Generated by Django 3.2.5 on 2021-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_model', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
