# Generated by Django 3.2.5 on 2021-07-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0002_auto_20210729_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealsmodel',
            options={'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.RenameField(
            model_name='dealsmodel',
            old_name='update_model',
            new_name='upload_deal',
        ),
    ]
