# Generated by Django 3.2.5 on 2021-08-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0003_auto_20210729_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFromDealsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=256)),
                ('item', models.CharField(max_length=256)),
                ('total', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
